export const COMPONENT_FIELDS = [
  "componentCode",
  "manufacturer",
  "brand",
  "series",
  "category",
  "subcategory",
  "partNumber",
  "model",
  "description",
  "ratedCurrent",
  "ratedVoltage",
  "poles",
  "breakingCapacity",
  "tripType",
  "coilVoltage",
  "powerKw",
  "frequency",
  "ipRating",
  "frameSize",
  "mountingType",
  "unit",
  "status",
  "notes",
] as const;
