import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import ExcelJS from "exceljs";
import { prisma } from "@/lib/db/prisma";
import { requirePermission, writeAuditLog } from "@/lib/auth/apiGuard";
import { date, normalizePricingIdentity, parsePricingHeaders, text, valueAt } from "@/lib/services/pricing/pricingImport";

export const runtime = "nodejs";
const currency = z.string().trim().regex(/^[A-Za-z]{3}$/).transform(v => v.toUpperCase());
const priceSchemaBase = z.object({ supplierId: z.string().min(1), componentId: z.string().min(1), price: z.number().finite().nonnegative(), currency: currency.default("EGP"), supplierPartNumber: z.string().trim().max(120).nullable().optional(), unit: z.string().trim().min(1).max(30).default("NO"), source: z.string().trim().max(500).nullable().optional(), active: z.boolean().default(true), effectiveFrom: z.string().datetime().optional(), effectiveTo: z.string().datetime().nullable().optional() });
const withValidDates = <T extends z.ZodTypeAny>(schema: T) => schema.refine((v: any) => !v.effectiveFrom || !v.effectiveTo || new Date(v.effectiveFrom) <= new Date(v.effectiveTo), { message: "Effective To must not precede Effective From", path: ["effectiveTo"] });
const priceSchema = withValidDates(priceSchemaBase);
const fail = (error: string, status: number, details: unknown[] = []) => NextResponse.json({ success: false, error, details }, { status });
const fileLike = (v: FormDataEntryValue | null): v is File => !!v && typeof v === "object" && "arrayBuffer" in v && "name" in v;

export async function GET(req: NextRequest) {
  const guard = await requirePermission("pricing.view"); if (guard.error) return guard.error;
  try {
    const p = new URL(req.url).searchParams, q = p.get("q")?.trim(), active = p.get("active"), category = p.get("category"), supplierId = p.get("supplierId"), sort = p.get("sort"), direction = p.get("direction") === "asc" ? "asc" : "desc";
    const rows = await prisma.supplierPrice.findMany({ where: { supplier: { deletedAt: null }, ...(supplierId ? { supplierId } : {}), ...(active === "true" || active === "false" ? { active: active === "true" } : {}), ...(category ? { component: { category: category as never } } : {}), ...(q ? { OR: [{ supplierPartNumber: { contains: q, mode: "insensitive" } }, { component: { partNumber: { contains: q, mode: "insensitive" } } }, { component: { description: { contains: q, mode: "insensitive" } } }, { supplier: { companyName: { contains: q, mode: "insensitive" } } }] } : {}) }, include: { supplier: true, component: true }, orderBy: sort === "price" ? { price: direction } : sort === "supplier" ? { supplier: { companyName: direction } } : { effectiveFrom: direction }, take: 500 });
    const [suppliers, components] = await Promise.all([prisma.party.findMany({ where: { type: "SUPPLIER", deletedAt: null }, orderBy: { companyName: "asc" } }), prisma.component.findMany({ where: { active: true }, orderBy: [{ manufacturer: "asc" }, { partNumber: "asc" }] })]);
    return NextResponse.json({ success: true, rows, suppliers, components });
  } catch (e) { console.error("Pricing GET", e); return fail("Unable to load pricing.", 500); }
}

export async function POST(req: NextRequest) {
  const guard = await requirePermission("pricing.edit"); if (guard.error) return guard.error;
  try { const parsed = priceSchema.safeParse(await req.json()); if (!parsed.success) return fail("Invalid price record.", 400, parsed.error.issues); const [supplier, component] = await Promise.all([prisma.party.findFirst({ where: { id: parsed.data.supplierId, type: "SUPPLIER", deletedAt: null } }), prisma.component.findFirst({ where: { id: parsed.data.componentId, active: true } })]); if (!supplier || !component) return fail("Supplier and active catalog component are required.", 400, [{ field: !supplier ? "supplierId" : "componentId", message: !supplier ? "Supplier does not exist or is inactive." : "Component does not exist or is inactive." }]); const { effectiveFrom, effectiveTo, ...data } = parsed.data; const price = await prisma.supplierPrice.create({ data: { ...data, effectiveFrom: effectiveFrom ? new Date(effectiveFrom) : new Date(), effectiveTo: effectiveTo ? new Date(effectiveTo) : null }, include: { supplier: true, component: true } }); await writeAuditLog({ userId: guard.userId, action: "SUPPLIER_PRICE_CREATED", entity: "SupplierPrice", entityId: price.id, newValue: price }); return NextResponse.json({ success: true, price }, { status: 201 }); } catch (e) { console.error("Pricing POST", e); return fail("Unable to create price.", 500); }
}
export async function PUT(req: NextRequest) {
  const guard = await requirePermission("pricing.edit"); if (guard.error) return guard.error;
  try { const parsed = withValidDates(priceSchemaBase.extend({ id: z.string().min(1) })).safeParse(await req.json()); if (!parsed.success) return fail("Invalid price record.", 400, parsed.error.issues); const { id, effectiveFrom, effectiveTo, ...data } = parsed.data; const price = await prisma.supplierPrice.update({ where: { id }, data: { ...data, effectiveFrom: effectiveFrom ? new Date(effectiveFrom) : new Date(), effectiveTo: effectiveTo ? new Date(effectiveTo) : null }, include: { supplier: true, component: true } }); return NextResponse.json({ success: true, price }); } catch (e) { console.error("Pricing PUT", e); return fail("Unable to update price.", 500); }
}
export async function DELETE(req: NextRequest) {
  const guard = await requirePermission("pricing.edit"); if (guard.error) return guard.error; const id = new URL(req.url).searchParams.get("id"); if (!id) return fail("Missing id.", 400);
  try { await prisma.supplierPrice.update({ where: { id }, data: { active: false } }); return NextResponse.json({ success: true }); } catch (e) { console.error("Pricing DELETE", e); return fail("Unable to deactivate price.", 500); }
}

export async function PATCH(req: NextRequest) {
  const guard = await requirePermission("pricing.edit"); if (guard.error) return guard.error;
  try {
    const form = await req.formData(), file = form.get("file");
    if (!fileLike(file) || file.size === 0) return fail("Attach a non-empty XLSX file in the 'file' field.", 400);
    if (!file.name.toLowerCase().endsWith(".xlsx") || (file.type && !["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/octet-stream"].includes(file.type))) return fail("Only XLSX files are supported.", 415);
    const buffer = Buffer.from(await file.arrayBuffer());
    if (buffer.length < 4 || buffer.subarray(0, 2).toString("ascii") !== "PK") return fail("The uploaded file is not a valid XLSX (ZIP) file.", 422);
    const workbook = new ExcelJS.Workbook(); try { await workbook.xlsx.load(buffer); } catch (e) { console.warn("Malformed XLSX", e); return fail("The XLSX file is malformed or unreadable.", 422); }
    const sheet = workbook.worksheets[0]; if (!sheet) return fail("The XLSX file contains no worksheet.", 422);
    const { columnMap, missing, ambiguous } = parsePricingHeaders(sheet);
    if (missing.length) return fail("Missing required pricing columns", 422, missing);
    if (ambiguous.length) return fail("Ambiguous pricing columns", 422, ambiguous.map(name => `Only one '${name}' column is allowed.`));
    const get = (row: ExcelJS.Row, name: Parameters<typeof valueAt>[2]) => valueAt(row, columnMap, name);
    const raw: any[] = [], errors: { row: number; field?: string; message: string }[] = [];
    for (let n = 2; n <= sheet.rowCount; n++) { const row = sheet.getRow(n); if ([...columnMap.values()].every(column => !text(row.getCell(column).value))) continue; const supplier = text(get(row, "supplier")), manufacturer = text(get(row, "manufacturer")), partNumber = text(get(row, "partNumber")), supplierPartNumber = text(get(row, "supplierPartNumber")), description = text(get(row, "description")), rawPrice = text(get(row, "price")); const price = Number(rawPrice.replace(/,/g, "")), currencyValue = (text(get(row, "currency")) || "EGP").toUpperCase(), fromValue = get(row, "effectiveFrom"), parsedFrom = date(fromValue), from = parsedFrom || new Date(), toValue = get(row, "effectiveTo"), to = toValue == null || !text(toValue) ? null : date(toValue); if (!supplier || (!partNumber && !supplierPartNumber && !description)) errors.push({ row: n, message: "Supplier and at least one of Part Number, Supplier SKU, or Description are required." }); else if (!Number.isFinite(price) || price < 0) errors.push({ row: n, field: "price", message: "Price must be a non-negative number." }); else if (fromValue != null && text(fromValue) && !parsedFrom) errors.push({ row: n, field: "effective from", message: "Effective From is not a valid date." }); else if (!/^[A-Z]{3}$/.test(currencyValue)) errors.push({ row: n, field: "currency", message: "Currency must be a three-letter ISO code." }); else if (toValue != null && text(toValue) && !to) errors.push({ row: n, field: "effective to", message: "Effective To is not a valid date." }); else if (to && to < from) errors.push({ row: n, field: "effective to", message: "Effective To must not precede Effective From." }); else raw.push({ row: n, supplier, manufacturer, partNumber, description, price, currency: currencyValue, supplierPartNumber: supplierPartNumber || null, unit: text(get(row, "unit")) || "NO", source: text(get(row, "source")) || `Excel import: ${file.name}`, active: !["false", "no", "0", "inactive"].includes(text(get(row, "active")).toLowerCase()), effectiveFrom: from, effectiveTo: to }); }
    if (!raw.length && !errors.length) return fail("The XLSX file contains no pricing rows.", 422);
    const [suppliers, components] = await Promise.all([prisma.party.findMany({ where: { type: "SUPPLIER", deletedAt: null } }), prisma.component.findMany({ where: { active: true } })]);
    const supplierIds = new Map(suppliers.map(s => [normalizePricingIdentity(s.companyName), s.id])); const seen = new Set<string>(), staged: any[] = [];
    const summary = { existingSuppliers: new Set<string>(), newSuppliers: new Set<string>(), existingComponents: new Set<string>(), newComponents: new Set<string>(), newPrices: 0, updatedPrices: 0 };
    for (const item of raw) { const supplierKey = normalizePricingIdentity(item.supplier), partKey = normalizePricingIdentity(item.partNumber || item.supplierPartNumber || item.description), manufacturerKey = normalizePricingIdentity(item.manufacturer), descriptionKey = normalizePricingIdentity(item.description); const componentKey = `${manufacturerKey}|${partKey}`; const component = components.find(c => manufacturerKey && partKey && normalizePricingIdentity(c.manufacturer) === manufacturerKey && normalizePricingIdentity(c.partNumber) === partKey) || (partKey ? (() => { const matches = components.filter(c => normalizePricingIdentity(c.partNumber) === partKey); return matches.length === 1 ? matches[0] : undefined; })() : undefined) || (descriptionKey ? (() => { const matches = components.filter(c => normalizePricingIdentity(c.description) === descriptionKey && (!manufacturerKey || normalizePricingIdentity(c.manufacturer) === manufacturerKey)); return matches.length === 1 ? matches[0] : undefined; })() : undefined); const duplicateKey = `${supplierKey}|${normalizePricingIdentity(item.supplierPartNumber || item.partNumber || item.description)}|${item.effectiveFrom.toISOString().slice(0, 10)}`; if (seen.has(duplicateKey)) errors.push({ row: item.row, field: "supplier part number", message: "Duplicate supplier SKU/part number for this supplier and effective date." }); else { seen.add(duplicateKey); if (supplierIds.has(supplierKey)) summary.existingSuppliers.add(supplierKey); else summary.newSuppliers.add(supplierKey); if (component) summary.existingComponents.add(component.id); else summary.newComponents.add(componentKey); staged.push({ ...item, supplierKey, componentKey, supplierId: supplierIds.get(supplierKey) ?? null, componentId: component?.id ?? null }); } }
    if (errors.length) return NextResponse.json({ success: false, error: "Import validation failed. No prices were changed.", created: 0, updated: 0, rejected: errors.length, errors }, { status: 422 });
    const mode = form.get("mode") === "replace" ? "replace" : form.get("mode") === "update" ? "update" : "append"; if (mode === "replace" && form.get("confirmReplace") !== "true") return fail("Replacement requires explicit confirmation.", 400);
    const resultSummary = { existingSuppliers: summary.existingSuppliers.size, newSuppliers: summary.newSuppliers.size, existingComponents: summary.existingComponents.size, newComponents: summary.newComponents.size, newPrices: staged.length, updatedPrices: 0 };
    if (form.get("dryRun") === "true") return NextResponse.json({ success: true, preview: true, message: "Import analysis completed. Confirm to make changes.", summary: resultSummary, created: 0, updated: 0, rejected: 0, errors: [] });
    let created = 0, updated = 0; await prisma.$transaction(async tx => { if (mode === "replace") await tx.supplierPrice.updateMany({ where: { active: true }, data: { active: false } }); const createdSuppliers = new Map<string, string>(), createdComponents = new Map<string, string>(); for (const item of staged) { let supplierId = item.supplierId || createdSuppliers.get(item.supplierKey); if (!supplierId) { const supplier = await tx.party.create({ data: { type: "SUPPLIER", companyName: item.supplier, country: "Egypt" } }); supplierId = supplier.id; createdSuppliers.set(item.supplierKey, supplierId); } let componentId = item.componentId || createdComponents.get(item.componentKey); if (!componentId) { const component = await tx.component.create({ data: { manufacturer: item.manufacturer || "Unspecified", partNumber: item.partNumber || item.supplierPartNumber || `IMPORTED-${createdComponents.size + 1}`, description: item.description || item.partNumber || item.supplierPartNumber, category: "OTHER", tags: ["IMPORTED"] } }); componentId = component.id; createdComponents.set(item.componentKey, componentId); } const supplierPartNumber = item.supplierPartNumber || item.partNumber || null; const existing = mode === "update" ? await tx.supplierPrice.findFirst({ where: { supplierId, componentId, supplierPartNumber, effectiveFrom: item.effectiveFrom } }) : null; const data = { supplierId, componentId, supplierPartNumber, price: item.price, currency: item.currency, unit: item.unit, source: item.source, active: item.active, effectiveFrom: item.effectiveFrom, effectiveTo: item.effectiveTo }; if (existing) { await tx.supplierPrice.update({ where: { id: existing.id }, data }); updated++; } else { if (mode !== "replace") await tx.supplierPrice.updateMany({ where: { supplierId, componentId, supplierPartNumber, active: true, effectiveFrom: { lt: item.effectiveFrom }, OR: [{ effectiveTo: null }, { effectiveTo: { gte: item.effectiveFrom } }] }, data: { active: false, effectiveTo: new Date(item.effectiveFrom.getTime() - 86400000) } }); await tx.supplierPrice.create({ data }); created++; } } });
    resultSummary.newPrices = created; resultSummary.updatedPrices = updated; await writeAuditLog({ userId: guard.userId, action: "SUPPLIER_PRICE_IMPORTED", entity: "SupplierPrice", entityId: "bulk", newValue: { mode, ...resultSummary } }); return NextResponse.json({ success: true, message: `Imported ${created} and updated ${updated} price record(s).`, summary: resultSummary, created, updated, rejected: 0, errors: [] });
  } catch (e) { console.error("Pricing PATCH", e); return fail("Unable to import pricing. No prices were changed.", 500); }
}
